"""initial schema: layers, facts, fact_versions

Revision ID: 2b53e2588f3e
Revises: 
Create Date: 2026-05-10 18:05:58.295104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '2b53e2588f3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


JSON_TYPE = sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'layers',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('display_name', sa.String(length=128), nullable=True),
        sa.Column('weight', sa.Integer(), nullable=False),
        sa.Column('ordinal', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint('weight >= 0 AND weight <= 100', name='ck_layers_weight_range'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_layers_name'),
        sa.UniqueConstraint('ordinal', name='uq_layers_ordinal'),
    )
    op.create_table(
        'facts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('layer_id', sa.Uuid(), nullable=False),
        sa.Column('schema_ref', sa.String(length=256), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_facts_layer_id'), 'facts', ['layer_id'], unique=False)
    op.create_table(
        'fact_versions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('fact_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', JSON_TYPE, nullable=False),
        sa.Column('weight', sa.Integer(), nullable=False),
        sa.Column('parent_fact_id', sa.Uuid(), nullable=True),
        sa.Column('parent_version_id', sa.Uuid(), nullable=True),
        sa.Column('justification', JSON_TYPE, nullable=True),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint('temperature IS NULL OR (temperature >= 0 AND temperature <= 1)', name='ck_fact_versions_temperature_range'),
        sa.CheckConstraint('version >= 1', name='ck_fact_versions_version_positive'),
        sa.CheckConstraint('weight >= 0 AND weight <= 100', name='ck_fact_versions_weight_range'),
        sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_fact_id'], ['facts.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['parent_version_id'], ['fact_versions.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('fact_id', 'version', name='uq_fact_versions_fact_version'),
    )
    op.create_index(op.f('ix_fact_versions_fact_id'), 'fact_versions', ['fact_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_versions_fact_id'), table_name='fact_versions')
    op.drop_table('fact_versions')
    op.drop_index(op.f('ix_facts_layer_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_table('layers')
    # ### end Alembic commands ###
